name: Npm Publish

on:
  push:
    branches:
      - main
    paths:
      - package.json
      - .github/workflows/npm-publish.yml
  workflow_dispatch:

jobs:
  main:
    uses: deep-foundation/workflows/.github/workflows/npm-publish.yml@npm-publish-4.0.0
    secrets:
      npm-token: ${{ secrets.NPM_TOKEN }}
    with:
      build-command: "npm run package:build"
      test-command: "echo 'Tests are temporarily disabled'"
      should-generate-documentation: true
      generate-documentation-command: "npx typedoc --out ./docs --entryPointStrategy expand ./imports"
