name: Npm Build

on:
  pull_request:
    types: [opened, reopened, edited]
  workflow_dispatch:

jobs:
  main:
    uses: deep-foundation/workflows/.github/workflows/npm-build.yml@main
    secrets:
      npm-token: ${{ secrets.NPM_TOKEN }}
    with:
      build-command: "npm run build"
